name: 'Terraform'

on:
  push:
    branches: [ "develop" ]
  pull_request:

permissions:
  contents: read

jobs: 
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    # Use the Bash shell regardless of the GitHub Actions runner type
    defaults:
      run:
        shell: bash

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v3

      # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.tfc_team_token }}

      # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
      - name: Terraform Init
        working-directory: example/
        run: terraform init 

      # Generates an execution plan for Terraform
      - name: Terraform Plan
        working-directory:  example/
        run: |
          terraform plan -input=false
        continue-on-error: true 

      # Note: It is recommended to set up a required "strict" status check in your repository for "Terraform Cloud".
      - name: Terraform Apply
        if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
        working-directory: example/
        run: terraform apply -auto-approve -input=false
