name: Terraform 

on:
  push:
    branches:
      - develop
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ matrix.terraform_version }}

      - name: Configure Terraform Credentials
        run: |
          echo 'credentials "app.terraform.io" {' > $HOME/.terraformrc
          echo '  token = "${{ secrets.tfc_team_token }}"' >> $HOME/.terraformrc
          echo '}' >> $HOME/.terraformrc

      - name: List Files in Working Directory
        run: |
          ls -R $GITHUB_WORKSPACE

      - name: Terraform Init
        run: |
          cd example/
          terraform init -upgrade -no-color -input=false

      - name: Terraform Plan
        run: |
          cd example/
          terraform plan -out=tfplan.out

      - name: Publish Terraform Plan Artifact
        uses: actions/upload-artifact@v2
        with:
          name: tfplan
          path: example/tfplan.out
