
name: 'Terraform'

on:
  push:
    branches: [ "feature/*","develop", "master" ]
  pull_request:
    types:
        - closed
  pull_request_review:
    types: [submitted]
  workflow_dispatch:

permissions:
  contents: read

jobs: 
  approved:
    if: github.event.review.state == 'APPROVED'
    runs-on: ubuntu-latest
    steps:
      - run: echo "This PR was approved"
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./examples/free-tier

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v3

      # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.tfc_team_token }}

      - name: Terraform Init
        run: terraform init 

      - name: Terraform Plan
        run: |
          terraform plan -input=false
        continue-on-error: true 
        
      - name: Terraform Apply
        if: github.event_name == 'pull_request' && github.event.pull_request.merged && github.event.pull_request.base.ref == 'master'
        run: |
          echo "The pull request was merged into the master branch."
          terraform apply -auto-approve -input=false

      - name: Terraform Destroy
        run: |
          terraform destroy -auto-approve
